{
 "title": "k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_min{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_max{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p50{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p75{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p90{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p95{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_p99{scenario=\"default\", status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_min{testid=~\"$testid\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_max{testid=~\"$testid\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p99{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}